#!/usr/bin/env bash

function list() {
    cat <<EOS
NAME                         USED  AVAIL  REFER  USEDSNAP
baracuda                    1.65T  1.03T  1.65T         0
rpool                       15.1G  94.2G    48K         0
rpool/ROOT                  2.99G  94.2G    31K         0
rpool/ROOT/april-2012       2.98G  94.2G  1.89G     1.09G
rpool/ROOT/openindiana      7.49M  94.2G  1.81G         0
rpool/dump                  5.86G  94.2G  5.86G         0
rpool/export                 608K  94.2G    32K         0
rpool/export/home            576K  94.2G    32K         0
rpool/export/home/pschultz   544K  94.2G   544K         0
rpool/swap                  6.23G   100G   133M         0
tank                        1.65T  2.36T  46.4K         0
tank/exports                1.65T  2.36T   415G         0
tank/exports/Audio          22.5G  2.36T  46.4K         0
tank/exports/Audio/Books    13.8G  2.36T  13.8G         0
tank/exports/Audio/Music    8.67G  2.36T  8.67G         0
tank/exports/Downloads       211G  2.36T   211G         0
tank/exports/Stuff          4.70M  2.36T  4.70M         0
tank/exports/Video          1.01T  2.36T  46.4K         0
tank/exports/Video/Movies    474G  2.36T   474G         0
tank/exports/Video/TvShows   564G  2.36T   564G         0
tank/homes                  1.05G  2.36T  50.9K         0
tank/homes/knox             2.08M  2.36T  2.08M         0
tank/homes/knox.old         1.04G  2.36T  1.04G         0
tank/homes/pschultz         10.9M  2.36T  10.9M         0
tank/homes/xbmc             43.4K  2.36T  43.4K         0
EOS
}

[ -z "$1" ] && echo "missing command" >&2 && exit 1;

case "$1" in
    status)
        status
        ;;
    list)
        # actually `zfs list -o name,used,available,refer,usedbysnapshots`
        list
        ;;
    *)
        echo "unrecognized command '$1'" >&2
        exit 2
        ;;
esac
