#!/usr/bin/env bash

function status() {
    cat <<EOS
  pool: pool
 state: ONLINE
  scan: none requested
config:

        NAME              STATE     READ WRITE CKSUM
        pool              ONLINE       0     0     0
          raidz1-0        ONLINE       0     0     0
            /dev/lofi/1   ONLINE       0     0     0
            /dev/lofi/2   ONLINE       0     0     0
            /dev/lofi/3   ONLINE       0     0     0
            /dev/lofi/4   ONLINE       0     0     0
          raidz1-1        ONLINE       0     0     0
            /dev/lofi/5   ONLINE       0     0     0
            /dev/lofi/6   ONLINE       0     0     0
            /dev/lofi/7   ONLINE       0     0     0
            /dev/lofi/8   ONLINE       0     0     0
          raidz1-2        ONLINE       0     0     0
            /dev/lofi/9   ONLINE       0     0     0
            /dev/lofi/10  ONLINE       0     0     0
            /dev/lofi/11  ONLINE       0     0     0
            /dev/lofi/12  ONLINE       0     0     0
          raidz1-3        ONLINE       0     0     0
            /dev/lofi/13  ONLINE       0     0     0
            /dev/lofi/14  ONLINE       0     0     0
            /dev/lofi/15  ONLINE       0     0     0
            /dev/lofi/16  ONLINE       0     0     0

errors: No known data errors

  pool: rpool
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        rpool       ONLINE       0     0     0
          c2d0s0    ONLINE       0     0     0

errors: No known data errors

  pool: tank
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: http://www.sun.com/msg/ZFS-8000-8A
  scan: scrub repaired 210M in 23h48m with 2178418 errors on Wed Apr 18 16:46:57 2012
config:

        NAME        STATE     READ WRITE CKSUM
        tank        DEGRADED     0     0  603K
          c4d1p0    ONLINE       0     0     4
          c4d0p0    DEGRADED     0     0 1.09M  too many errors
          c4d0      DEGRADED     0     0  197K  too many errors
          c6d0      ONLINE       0     0     0

errors: 2564646 data errors, use '-v' for a list
EOS
}

function list() {
    cat <<EOS
NAME       SIZE  ALLOC   FREE  EXPANDSZ    CAP  DEDUP  HEALTH  ALTROOT
pool      23.2G   184K  23.2G         -     0%  1.00x  ONLINE  -
rpool      111G  6.55G   104G         -     5%  1.00x  ONLINE  -
tank      4.99T  2.87T  2.12T     10.5E    57%  1.00x  DEGRADED  -
EOS
}

[ -z "$1" ] && echo "missing command" >&2 && exit 1;

case "$1" in
    status)
        status
        ;;
    list)
        list
        ;;
    *)
        echo "unrecognized command '$1'" >&2
        exit 2
        ;;
esac
